POST http://localhost:8080/event
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjEzNTRAZXhhYW1wbGUuY29tIiwiZXhwIjoxNzY2NjU4NjcwLCJ1c2VySWQiOjV9.8tS4DIrTiy6H8yeLNqenrnk0qwvEhi_ity0nLvSxdS0

{
  "name": "Annual Meeting",
  "location": "New York City",
  "description": "An event to discuss annual performance and future plans."
}